name: Test Docker Build

on:
  push:
    branches: [ ros1 ]
  pull_request:
    branches: [ ros1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t knowrob/ros1 .
