name: Test Docker Build

on:
  push:
    branches: [ ros1 ]
  pull_request:
    branches: [ ros1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t knowrob/ros1 .

    - name: Run roslaunch to test if it starts without error
      run: |
        docker run --rm knowrob/ros1 timeout 30s bash -c "/run_knowrob_local.sh"
